name: Deploy to Firebase Hosting

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - run: npm run build

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/436171679854/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions-deploy@sefbot-designer.iam.gserviceaccount.com

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ steps.auth.outputs.credentials_file_path }}
          channelId: live
          projectId: sefbot-designer
